ARG NODE_BASE_IMAGE=docker.1ms.run/node:20-alpine
ARG NGINX_BASE_IMAGE=docker.1ms.run/nginx:1.27-alpine
FROM ${NODE_BASE_IMAGE} AS builder

ARG NPM_REGISTRY=https://registry.npmmirror.com

WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm config set registry ${NPM_REGISTRY} && npm install
COPY . .
RUN npm run build

FROM ${NGINX_BASE_IMAGE}
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
